version: "3"

services:
    proxy:
        build:
            context: .
            dockerfile: docker/proxy/Dockerfile
        ports:
            - "443:443"
            - "8080:8080"
            - "8888:8888"
        privileged: true
        network_mode: "host"
    filter:
        build:
            context: .
            dockerfile: docker/filter/Dockerfile
        ports:
            - "8081:8081"

